/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        CuteQueue cuteQueue = new CuteQueue(2); // capacity 2
        
        Puppy puppy1 = new Puppy();
        Puppy puppy2 = new Puppy();
        Puppy puppy3 = new Puppy();
        
        cuteQueue.enqueue(puppy1);
        cuteQueue.enqueue(puppy2);
        
        System.out.println("Current queue size: " + cuteQueue.size()); // Should print 2
        
        cuteQueue.enqueue(puppy3); // Should print "Queue is full!"
        
        Cutie firstCutie = cuteQueue.dequeue();
        System.out.println("Dequeued: " + firstCutie.description()); // Info about puppy1
        
        System.out.println("Current queue size: " + cuteQueue.size()); // Should print 1
    }
}

